export const skills = {
  languages: ["JavaScript (ES6+)", "TypeScript", "Solidity"],
  frontend: [
    "React.js",
    "Next.js",
    "Redux Toolkit",
    "Tailwind CSS",
    "Material UI",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "RESTful APIs",
    "Socket.IO",
    "JWT / OAuth",
  ],
  data: ["MongoDB", "Redis", "Prisma", "Mongoose", "SQLite"],
  cloud: [
    "AWS",
    "Load Balancers",
    "Vercel",
    "Render",
    "Cloudinary",
  ],
  devops: [
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "CI/CD Pipelines",
  ],
  ai: [
    "Google Gemini",
    "Hugging Face",
    "Anthropic",
    "OpenAI",
    "Groq",
  ],
  tools: ["Git", "GitHub", "Postman", "Linux", "Nginx"],
};
